//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMPSTransactionRouter.FCUBSMessagingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://types.ws.gw.fcubs.ofss.com", ConfigurationName="FCUBSMessagingService.FCUBSMessagingServiceSEI")]
    public interface FCUBSMessagingServiceSEI {
        
        // CODEGEN: Generating message contract since the operation GetContractMsgsIO is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IMPSTransactionRouter.FCUBSMessagingService.GetContractMsgsIOResponse GetContractMsgsIO(IMPSTransactionRouter.FCUBSMessagingService.GetContractMsgsIORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<IMPSTransactionRouter.FCUBSMessagingService.GetContractMsgsIOResponse> GetContractMsgsIOAsync(IMPSTransactionRouter.FCUBSMessagingService.GetContractMsgsIORequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fcubs.ofss.com/service/FCUBSMessagingService")]
    public partial class GETCONTRACTMSGS_IOFS_REQ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FCUBS_HEADERType fCUBS_HEADERField;
        
        private GETCONTRACTMSGS_IOFS_REQFCUBS_BODY fCUBS_BODYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FCUBS_HEADERType FCUBS_HEADER {
            get {
                return this.fCUBS_HEADERField;
            }
            set {
                this.fCUBS_HEADERField = value;
                this.RaisePropertyChanged("FCUBS_HEADER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public GETCONTRACTMSGS_IOFS_REQFCUBS_BODY FCUBS_BODY {
            get {
                return this.fCUBS_BODYField;
            }
            set {
                this.fCUBS_BODYField = value;
                this.RaisePropertyChanged("FCUBS_BODY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSMessagingService")]
    public partial class FCUBS_HEADERType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sOURCEField;
        
        private UBSCOMPType uBSCOMPField;
        
        private string mSGIDField;
        
        private string cORRELIDField;
        
        private string uSERIDField;
        
        private string bRANCHField;
        
        private string mODULEIDField;
        
        private string sERVICEField;
        
        private string oPERATIONField;
        
        private string sOURCE_OPERATIONField;
        
        private string sOURCE_USERIDField;
        
        private string dESTINATIONField;
        
        private string mULTITRIPIDField;
        
        private string fUNCTIONIDField;
        
        private string aCTIONField;
        
        private MsgStatType mSGSTATField;
        
        private bool mSGSTATFieldSpecified;
        
        private string pASSWORDField;
        
        private FCUBS_HEADERTypePARAM[] aDDLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SOURCE {
            get {
                return this.sOURCEField;
            }
            set {
                this.sOURCEField = value;
                this.RaisePropertyChanged("SOURCE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public UBSCOMPType UBSCOMP {
            get {
                return this.uBSCOMPField;
            }
            set {
                this.uBSCOMPField = value;
                this.RaisePropertyChanged("UBSCOMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MSGID {
            get {
                return this.mSGIDField;
            }
            set {
                this.mSGIDField = value;
                this.RaisePropertyChanged("MSGID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CORRELID {
            get {
                return this.cORRELIDField;
            }
            set {
                this.cORRELIDField = value;
                this.RaisePropertyChanged("CORRELID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string USERID {
            get {
                return this.uSERIDField;
            }
            set {
                this.uSERIDField = value;
                this.RaisePropertyChanged("USERID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BRANCH {
            get {
                return this.bRANCHField;
            }
            set {
                this.bRANCHField = value;
                this.RaisePropertyChanged("BRANCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MODULEID {
            get {
                return this.mODULEIDField;
            }
            set {
                this.mODULEIDField = value;
                this.RaisePropertyChanged("MODULEID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string SERVICE {
            get {
                return this.sERVICEField;
            }
            set {
                this.sERVICEField = value;
                this.RaisePropertyChanged("SERVICE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string OPERATION {
            get {
                return this.oPERATIONField;
            }
            set {
                this.oPERATIONField = value;
                this.RaisePropertyChanged("OPERATION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SOURCE_OPERATION {
            get {
                return this.sOURCE_OPERATIONField;
            }
            set {
                this.sOURCE_OPERATIONField = value;
                this.RaisePropertyChanged("SOURCE_OPERATION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string SOURCE_USERID {
            get {
                return this.sOURCE_USERIDField;
            }
            set {
                this.sOURCE_USERIDField = value;
                this.RaisePropertyChanged("SOURCE_USERID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string DESTINATION {
            get {
                return this.dESTINATIONField;
            }
            set {
                this.dESTINATIONField = value;
                this.RaisePropertyChanged("DESTINATION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string MULTITRIPID {
            get {
                return this.mULTITRIPIDField;
            }
            set {
                this.mULTITRIPIDField = value;
                this.RaisePropertyChanged("MULTITRIPID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string FUNCTIONID {
            get {
                return this.fUNCTIONIDField;
            }
            set {
                this.fUNCTIONIDField = value;
                this.RaisePropertyChanged("FUNCTIONID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ACTION {
            get {
                return this.aCTIONField;
            }
            set {
                this.aCTIONField = value;
                this.RaisePropertyChanged("ACTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public MsgStatType MSGSTAT {
            get {
                return this.mSGSTATField;
            }
            set {
                this.mSGSTATField = value;
                this.RaisePropertyChanged("MSGSTAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MSGSTATSpecified {
            get {
                return this.mSGSTATFieldSpecified;
            }
            set {
                this.mSGSTATFieldSpecified = value;
                this.RaisePropertyChanged("MSGSTATSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string PASSWORD {
            get {
                return this.pASSWORDField;
            }
            set {
                this.pASSWORDField = value;
                this.RaisePropertyChanged("PASSWORD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=17)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PARAM", IsNullable=false)]
        public FCUBS_HEADERTypePARAM[] ADDL {
            get {
                return this.aDDLField;
            }
            set {
                this.aDDLField = value;
                this.RaisePropertyChanged("ADDL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSMessagingService")]
    public enum UBSCOMPType {
        
        /// <remarks/>
        FCUBS,
        
        /// <remarks/>
        FCIS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSMessagingService")]
    public enum MsgStatType {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        WARNING,
        
        /// <remarks/>
        FAILURE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fcubs.ofss.com/service/FCUBSMessagingService")]
    public partial class FCUBS_HEADERTypePARAM : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nAMEField;
        
        private string vALUEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
                this.RaisePropertyChanged("NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VALUE {
            get {
                return this.vALUEField;
            }
            set {
                this.vALUEField = value;
                this.RaisePropertyChanged("VALUE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSMessagingService")]
    public partial class WARNINGDETAILSType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wCODEField;
        
        private string wDESCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string WCODE {
            get {
                return this.wCODEField;
            }
            set {
                this.wCODEField = value;
                this.RaisePropertyChanged("WCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string WDESC {
            get {
                return this.wDESCField;
            }
            set {
                this.wDESCField = value;
                this.RaisePropertyChanged("WDESC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSMessagingService")]
    public partial class ERRORDETAILSType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eCODEField;
        
        private string eDESCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ECODE {
            get {
                return this.eCODEField;
            }
            set {
                this.eCODEField = value;
                this.RaisePropertyChanged("ECODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EDESC {
            get {
                return this.eDESCField;
            }
            set {
                this.eDESCField = value;
                this.RaisePropertyChanged("EDESC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ContractMsgs-Full-Type", Namespace="http://fcubs.ofss.com/service/FCUBSMessagingService")]
    public partial class ContractMsgsFullType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fCCREFField;
        
        private ContractMsgsFullTypeMessageDetails[] messageDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FCCREF {
            get {
                return this.fCCREFField;
            }
            set {
                this.fCCREFField = value;
                this.RaisePropertyChanged("FCCREF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MessageDetails", Order=1)]
        public ContractMsgsFullTypeMessageDetails[] MessageDetails {
            get {
                return this.messageDetailsField;
            }
            set {
                this.messageDetailsField = value;
                this.RaisePropertyChanged("MessageDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fcubs.ofss.com/service/FCUBSMessagingService")]
    public partial class ContractMsgsFullTypeMessageDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal eSNField;
        
        private bool eSNFieldSpecified;
        
        private string mSGTYPEField;
        
        private string rECEIVERField;
        
        private string mSGSTATUSField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal ESN {
            get {
                return this.eSNField;
            }
            set {
                this.eSNField = value;
                this.RaisePropertyChanged("ESN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ESNSpecified {
            get {
                return this.eSNFieldSpecified;
            }
            set {
                this.eSNFieldSpecified = value;
                this.RaisePropertyChanged("ESNSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MSGTYPE {
            get {
                return this.mSGTYPEField;
            }
            set {
                this.mSGTYPEField = value;
                this.RaisePropertyChanged("MSGTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RECEIVER {
            get {
                return this.rECEIVERField;
            }
            set {
                this.rECEIVERField = value;
                this.RaisePropertyChanged("RECEIVER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MSGSTATUS {
            get {
                return this.mSGSTATUSField;
            }
            set {
                this.mSGSTATUSField = value;
                this.RaisePropertyChanged("MSGSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ContractMsgs-IO-Type", Namespace="http://fcubs.ofss.com/service/FCUBSMessagingService")]
    public partial class ContractMsgsIOType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fCCREFField;
        
        private ContractMsgsIOTypeMessageDetails[] messageDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FCCREF {
            get {
                return this.fCCREFField;
            }
            set {
                this.fCCREFField = value;
                this.RaisePropertyChanged("FCCREF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MessageDetails", Order=1)]
        public ContractMsgsIOTypeMessageDetails[] MessageDetails {
            get {
                return this.messageDetailsField;
            }
            set {
                this.messageDetailsField = value;
                this.RaisePropertyChanged("MessageDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fcubs.ofss.com/service/FCUBSMessagingService")]
    public partial class ContractMsgsIOTypeMessageDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal eSNField;
        
        private bool eSNFieldSpecified;
        
        private string mSGTYPEField;
        
        private string rECEIVERField;
        
        private string mSGSTATUSField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal ESN {
            get {
                return this.eSNField;
            }
            set {
                this.eSNField = value;
                this.RaisePropertyChanged("ESN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ESNSpecified {
            get {
                return this.eSNFieldSpecified;
            }
            set {
                this.eSNFieldSpecified = value;
                this.RaisePropertyChanged("ESNSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MSGTYPE {
            get {
                return this.mSGTYPEField;
            }
            set {
                this.mSGTYPEField = value;
                this.RaisePropertyChanged("MSGTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RECEIVER {
            get {
                return this.rECEIVERField;
            }
            set {
                this.rECEIVERField = value;
                this.RaisePropertyChanged("RECEIVER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MSGSTATUS {
            get {
                return this.mSGSTATUSField;
            }
            set {
                this.mSGSTATUSField = value;
                this.RaisePropertyChanged("MSGSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ContractMsgs-PK-Type", Namespace="http://fcubs.ofss.com/service/FCUBSMessagingService")]
    public partial class ContractMsgsPKType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fCCREFField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FCCREF {
            get {
                return this.fCCREFField;
            }
            set {
                this.fCCREFField = value;
                this.RaisePropertyChanged("FCCREF");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fcubs.ofss.com/service/FCUBSMessagingService")]
    public partial class GETCONTRACTMSGS_IOFS_REQFCUBS_BODY : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ContractMsgsPKType contractMessagesIOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContractMessages-IO", Order=0)]
        public ContractMsgsPKType ContractMessagesIO {
            get {
                return this.contractMessagesIOField;
            }
            set {
                this.contractMessagesIOField = value;
                this.RaisePropertyChanged("ContractMessagesIO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fcubs.ofss.com/service/FCUBSMessagingService")]
    public partial class GETCONTRACTMSGS_IOFS_RES : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FCUBS_HEADERType fCUBS_HEADERField;
        
        private GETCONTRACTMSGS_IOFS_RESFCUBS_BODY fCUBS_BODYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FCUBS_HEADERType FCUBS_HEADER {
            get {
                return this.fCUBS_HEADERField;
            }
            set {
                this.fCUBS_HEADERField = value;
                this.RaisePropertyChanged("FCUBS_HEADER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public GETCONTRACTMSGS_IOFS_RESFCUBS_BODY FCUBS_BODY {
            get {
                return this.fCUBS_BODYField;
            }
            set {
                this.fCUBS_BODYField = value;
                this.RaisePropertyChanged("FCUBS_BODY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fcubs.ofss.com/service/FCUBSMessagingService")]
    public partial class GETCONTRACTMSGS_IOFS_RESFCUBS_BODY : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ContractMsgsPKType contractMessagesPKField;
        
        private ContractMsgsIOType contractMessagesIOField;
        
        private ContractMsgsFullType contractMessagesFullField;
        
        private ERRORDETAILSType[] fCUBS_ERROR_RESPField;
        
        private WARNINGDETAILSType[] fCUBS_WARNING_RESPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContractMessages-PK", Order=0)]
        public ContractMsgsPKType ContractMessagesPK {
            get {
                return this.contractMessagesPKField;
            }
            set {
                this.contractMessagesPKField = value;
                this.RaisePropertyChanged("ContractMessagesPK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContractMessages-IO", Order=1)]
        public ContractMsgsIOType ContractMessagesIO {
            get {
                return this.contractMessagesIOField;
            }
            set {
                this.contractMessagesIOField = value;
                this.RaisePropertyChanged("ContractMessagesIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContractMessages-Full", Order=2)]
        public ContractMsgsFullType ContractMessagesFull {
            get {
                return this.contractMessagesFullField;
            }
            set {
                this.contractMessagesFullField = value;
                this.RaisePropertyChanged("ContractMessagesFull");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ERROR", typeof(ERRORDETAILSType), IsNullable=false)]
        public ERRORDETAILSType[] FCUBS_ERROR_RESP {
            get {
                return this.fCUBS_ERROR_RESPField;
            }
            set {
                this.fCUBS_ERROR_RESPField = value;
                this.RaisePropertyChanged("FCUBS_ERROR_RESP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("WARNING", typeof(WARNINGDETAILSType), IsNullable=false)]
        public WARNINGDETAILSType[] FCUBS_WARNING_RESP {
            get {
                return this.fCUBS_WARNING_RESPField;
            }
            set {
                this.fCUBS_WARNING_RESPField = value;
                this.RaisePropertyChanged("FCUBS_WARNING_RESP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContractMsgsIORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSMessagingService", Order=0)]
        public IMPSTransactionRouter.FCUBSMessagingService.GETCONTRACTMSGS_IOFS_REQ GETCONTRACTMSGS_IOFS_REQ;
        
        public GetContractMsgsIORequest() {
        }
        
        public GetContractMsgsIORequest(IMPSTransactionRouter.FCUBSMessagingService.GETCONTRACTMSGS_IOFS_REQ GETCONTRACTMSGS_IOFS_REQ) {
            this.GETCONTRACTMSGS_IOFS_REQ = GETCONTRACTMSGS_IOFS_REQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContractMsgsIOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSMessagingService", Order=0)]
        public IMPSTransactionRouter.FCUBSMessagingService.GETCONTRACTMSGS_IOFS_RES GETCONTRACTMSGS_IOFS_RES;
        
        public GetContractMsgsIOResponse() {
        }
        
        public GetContractMsgsIOResponse(IMPSTransactionRouter.FCUBSMessagingService.GETCONTRACTMSGS_IOFS_RES GETCONTRACTMSGS_IOFS_RES) {
            this.GETCONTRACTMSGS_IOFS_RES = GETCONTRACTMSGS_IOFS_RES;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FCUBSMessagingServiceSEIChannel : IMPSTransactionRouter.FCUBSMessagingService.FCUBSMessagingServiceSEI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FCUBSMessagingServiceSEIClient : System.ServiceModel.ClientBase<IMPSTransactionRouter.FCUBSMessagingService.FCUBSMessagingServiceSEI>, IMPSTransactionRouter.FCUBSMessagingService.FCUBSMessagingServiceSEI {
        
        public FCUBSMessagingServiceSEIClient() {
        }
        
        public FCUBSMessagingServiceSEIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FCUBSMessagingServiceSEIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FCUBSMessagingServiceSEIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FCUBSMessagingServiceSEIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IMPSTransactionRouter.FCUBSMessagingService.GetContractMsgsIOResponse IMPSTransactionRouter.FCUBSMessagingService.FCUBSMessagingServiceSEI.GetContractMsgsIO(IMPSTransactionRouter.FCUBSMessagingService.GetContractMsgsIORequest request) {
            return base.Channel.GetContractMsgsIO(request);
        }
        
        public IMPSTransactionRouter.FCUBSMessagingService.GETCONTRACTMSGS_IOFS_RES GetContractMsgsIO(IMPSTransactionRouter.FCUBSMessagingService.GETCONTRACTMSGS_IOFS_REQ GETCONTRACTMSGS_IOFS_REQ) {
            IMPSTransactionRouter.FCUBSMessagingService.GetContractMsgsIORequest inValue = new IMPSTransactionRouter.FCUBSMessagingService.GetContractMsgsIORequest();
            inValue.GETCONTRACTMSGS_IOFS_REQ = GETCONTRACTMSGS_IOFS_REQ;
            IMPSTransactionRouter.FCUBSMessagingService.GetContractMsgsIOResponse retVal = ((IMPSTransactionRouter.FCUBSMessagingService.FCUBSMessagingServiceSEI)(this)).GetContractMsgsIO(inValue);
            return retVal.GETCONTRACTMSGS_IOFS_RES;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IMPSTransactionRouter.FCUBSMessagingService.GetContractMsgsIOResponse> IMPSTransactionRouter.FCUBSMessagingService.FCUBSMessagingServiceSEI.GetContractMsgsIOAsync(IMPSTransactionRouter.FCUBSMessagingService.GetContractMsgsIORequest request) {
            return base.Channel.GetContractMsgsIOAsync(request);
        }
        
        public System.Threading.Tasks.Task<IMPSTransactionRouter.FCUBSMessagingService.GetContractMsgsIOResponse> GetContractMsgsIOAsync(IMPSTransactionRouter.FCUBSMessagingService.GETCONTRACTMSGS_IOFS_REQ GETCONTRACTMSGS_IOFS_REQ) {
            IMPSTransactionRouter.FCUBSMessagingService.GetContractMsgsIORequest inValue = new IMPSTransactionRouter.FCUBSMessagingService.GetContractMsgsIORequest();
            inValue.GETCONTRACTMSGS_IOFS_REQ = GETCONTRACTMSGS_IOFS_REQ;
            return ((IMPSTransactionRouter.FCUBSMessagingService.FCUBSMessagingServiceSEI)(this)).GetContractMsgsIOAsync(inValue);
        }
    }
}
