//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMPSTransactionRouter.FCUBSAccFinService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://types.ws.gw.fcubs.ofss.com", ConfigurationName="FCUBSAccFinService.FCUBSAccFinServiceSEI")]
    public interface FCUBSAccFinServiceSEI {
        
        // CODEGEN: Generating message contract since the operation FinancialCycleQueryIO is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IMPSTransactionRouter.FCUBSAccFinService.FinancialCycleQueryIOResponse FinancialCycleQueryIO(IMPSTransactionRouter.FCUBSAccFinService.FinancialCycleQueryIORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<IMPSTransactionRouter.FCUBSAccFinService.FinancialCycleQueryIOResponse> FinancialCycleQueryIOAsync(IMPSTransactionRouter.FCUBSAccFinService.FinancialCycleQueryIORequest request);
        
        // CODEGEN: Generating message contract since the operation QueryFinancialCycleIO is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IMPSTransactionRouter.FCUBSAccFinService.QueryFinancialCycleIOResponse QueryFinancialCycleIO(IMPSTransactionRouter.FCUBSAccFinService.QueryFinancialCycleIORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<IMPSTransactionRouter.FCUBSAccFinService.QueryFinancialCycleIOResponse> QueryFinancialCycleIOAsync(IMPSTransactionRouter.FCUBSAccFinService.QueryFinancialCycleIORequest request);
        
        // CODEGEN: Generating message contract since the operation RequestAccStmtIO is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IMPSTransactionRouter.FCUBSAccFinService.RequestAccStmtIOResponse RequestAccStmtIO(IMPSTransactionRouter.FCUBSAccFinService.RequestAccStmtIORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<IMPSTransactionRouter.FCUBSAccFinService.RequestAccStmtIOResponse> RequestAccStmtIOAsync(IMPSTransactionRouter.FCUBSAccFinService.RequestAccStmtIORequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public partial class FINANCIALCYCLEQUERY_IOFS_REQ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FCUBS_HEADERType fCUBS_HEADERField;
        
        private FINANCIALCYCLEQUERY_IOFS_REQFCUBS_BODY fCUBS_BODYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FCUBS_HEADERType FCUBS_HEADER {
            get {
                return this.fCUBS_HEADERField;
            }
            set {
                this.fCUBS_HEADERField = value;
                this.RaisePropertyChanged("FCUBS_HEADER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FINANCIALCYCLEQUERY_IOFS_REQFCUBS_BODY FCUBS_BODY {
            get {
                return this.fCUBS_BODYField;
            }
            set {
                this.fCUBS_BODYField = value;
                this.RaisePropertyChanged("FCUBS_BODY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public partial class FCUBS_HEADERType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sOURCEField;
        
        private UBSCOMPType uBSCOMPField;
        
        private string mSGIDField;
        
        private string cORRELIDField;
        
        private string uSERIDField;
        
        private string bRANCHField;
        
        private string mODULEIDField;
        
        private string sERVICEField;
        
        private string oPERATIONField;
        
        private string sOURCE_OPERATIONField;
        
        private string sOURCE_USERIDField;
        
        private string dESTINATIONField;
        
        private string mULTITRIPIDField;
        
        private string fUNCTIONIDField;
        
        private string aCTIONField;
        
        private MsgStatType mSGSTATField;
        
        private bool mSGSTATFieldSpecified;
        
        private string pASSWORDField;
        
        private FCUBS_HEADERTypePARAM[] aDDLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SOURCE {
            get {
                return this.sOURCEField;
            }
            set {
                this.sOURCEField = value;
                this.RaisePropertyChanged("SOURCE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public UBSCOMPType UBSCOMP {
            get {
                return this.uBSCOMPField;
            }
            set {
                this.uBSCOMPField = value;
                this.RaisePropertyChanged("UBSCOMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MSGID {
            get {
                return this.mSGIDField;
            }
            set {
                this.mSGIDField = value;
                this.RaisePropertyChanged("MSGID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CORRELID {
            get {
                return this.cORRELIDField;
            }
            set {
                this.cORRELIDField = value;
                this.RaisePropertyChanged("CORRELID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string USERID {
            get {
                return this.uSERIDField;
            }
            set {
                this.uSERIDField = value;
                this.RaisePropertyChanged("USERID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BRANCH {
            get {
                return this.bRANCHField;
            }
            set {
                this.bRANCHField = value;
                this.RaisePropertyChanged("BRANCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MODULEID {
            get {
                return this.mODULEIDField;
            }
            set {
                this.mODULEIDField = value;
                this.RaisePropertyChanged("MODULEID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string SERVICE {
            get {
                return this.sERVICEField;
            }
            set {
                this.sERVICEField = value;
                this.RaisePropertyChanged("SERVICE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string OPERATION {
            get {
                return this.oPERATIONField;
            }
            set {
                this.oPERATIONField = value;
                this.RaisePropertyChanged("OPERATION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SOURCE_OPERATION {
            get {
                return this.sOURCE_OPERATIONField;
            }
            set {
                this.sOURCE_OPERATIONField = value;
                this.RaisePropertyChanged("SOURCE_OPERATION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string SOURCE_USERID {
            get {
                return this.sOURCE_USERIDField;
            }
            set {
                this.sOURCE_USERIDField = value;
                this.RaisePropertyChanged("SOURCE_USERID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string DESTINATION {
            get {
                return this.dESTINATIONField;
            }
            set {
                this.dESTINATIONField = value;
                this.RaisePropertyChanged("DESTINATION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string MULTITRIPID {
            get {
                return this.mULTITRIPIDField;
            }
            set {
                this.mULTITRIPIDField = value;
                this.RaisePropertyChanged("MULTITRIPID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string FUNCTIONID {
            get {
                return this.fUNCTIONIDField;
            }
            set {
                this.fUNCTIONIDField = value;
                this.RaisePropertyChanged("FUNCTIONID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ACTION {
            get {
                return this.aCTIONField;
            }
            set {
                this.aCTIONField = value;
                this.RaisePropertyChanged("ACTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public MsgStatType MSGSTAT {
            get {
                return this.mSGSTATField;
            }
            set {
                this.mSGSTATField = value;
                this.RaisePropertyChanged("MSGSTAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MSGSTATSpecified {
            get {
                return this.mSGSTATFieldSpecified;
            }
            set {
                this.mSGSTATFieldSpecified = value;
                this.RaisePropertyChanged("MSGSTATSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string PASSWORD {
            get {
                return this.pASSWORDField;
            }
            set {
                this.pASSWORDField = value;
                this.RaisePropertyChanged("PASSWORD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=17)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PARAM", IsNullable=false)]
        public FCUBS_HEADERTypePARAM[] ADDL {
            get {
                return this.aDDLField;
            }
            set {
                this.aDDLField = value;
                this.RaisePropertyChanged("ADDL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public enum UBSCOMPType {
        
        /// <remarks/>
        FCUBS,
        
        /// <remarks/>
        FCIS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public enum MsgStatType {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        WARNING,
        
        /// <remarks/>
        FAILURE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public partial class FCUBS_HEADERTypePARAM : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nAMEField;
        
        private string vALUEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
                this.RaisePropertyChanged("NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VALUE {
            get {
                return this.vALUEField;
            }
            set {
                this.vALUEField = value;
                this.RaisePropertyChanged("VALUE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public partial class AdhocStmtResType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string xREFField;
        
        private string dCNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string XREF {
            get {
                return this.xREFField;
            }
            set {
                this.xREFField = value;
                this.RaisePropertyChanged("XREF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DCN {
            get {
                return this.dCNField;
            }
            set {
                this.dCNField = value;
                this.RaisePropertyChanged("DCN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public partial class AdhocStmtReqType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string xREFField;
        
        private string aCCField;
        
        private string bRNField;
        
        private System.DateTime fRMDTField;
        
        private bool fRMDTFieldSpecified;
        
        private System.DateTime tODTField;
        
        private bool tODTFieldSpecified;
        
        private StmtType sTMTTYPEField;
        
        private bool sTMTTYPEFieldSpecified;
        
        private BalanceType bALANCETYPEField;
        
        private bool bALANCETYPEFieldSpecified;
        
        private YesNoType aPPLYCHGField;
        
        private bool aPPLYCHGFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string XREF {
            get {
                return this.xREFField;
            }
            set {
                this.xREFField = value;
                this.RaisePropertyChanged("XREF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ACC {
            get {
                return this.aCCField;
            }
            set {
                this.aCCField = value;
                this.RaisePropertyChanged("ACC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BRN {
            get {
                return this.bRNField;
            }
            set {
                this.bRNField = value;
                this.RaisePropertyChanged("BRN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime FRMDT {
            get {
                return this.fRMDTField;
            }
            set {
                this.fRMDTField = value;
                this.RaisePropertyChanged("FRMDT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FRMDTSpecified {
            get {
                return this.fRMDTFieldSpecified;
            }
            set {
                this.fRMDTFieldSpecified = value;
                this.RaisePropertyChanged("FRMDTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime TODT {
            get {
                return this.tODTField;
            }
            set {
                this.tODTField = value;
                this.RaisePropertyChanged("TODT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TODTSpecified {
            get {
                return this.tODTFieldSpecified;
            }
            set {
                this.tODTFieldSpecified = value;
                this.RaisePropertyChanged("TODTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public StmtType STMTTYPE {
            get {
                return this.sTMTTYPEField;
            }
            set {
                this.sTMTTYPEField = value;
                this.RaisePropertyChanged("STMTTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool STMTTYPESpecified {
            get {
                return this.sTMTTYPEFieldSpecified;
            }
            set {
                this.sTMTTYPEFieldSpecified = value;
                this.RaisePropertyChanged("STMTTYPESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public BalanceType BALANCETYPE {
            get {
                return this.bALANCETYPEField;
            }
            set {
                this.bALANCETYPEField = value;
                this.RaisePropertyChanged("BALANCETYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BALANCETYPESpecified {
            get {
                return this.bALANCETYPEFieldSpecified;
            }
            set {
                this.bALANCETYPEFieldSpecified = value;
                this.RaisePropertyChanged("BALANCETYPESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public YesNoType APPLYCHG {
            get {
                return this.aPPLYCHGField;
            }
            set {
                this.aPPLYCHGField = value;
                this.RaisePropertyChanged("APPLYCHG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool APPLYCHGSpecified {
            get {
                return this.aPPLYCHGFieldSpecified;
            }
            set {
                this.aPPLYCHGFieldSpecified = value;
                this.RaisePropertyChanged("APPLYCHGSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public enum StmtType {
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        D,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public enum BalanceType {
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        V,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public enum YesNoType {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="FinancialCycle-Query-IO-Type", Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public partial class FinancialCycleQueryIOType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fINCLEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FINCLE {
            get {
                return this.fINCLEField;
            }
            set {
                this.fINCLEField = value;
                this.RaisePropertyChanged("FINCLE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public partial class WARNINGDETAILSType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wCODEField;
        
        private string wDESCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string WCODE {
            get {
                return this.wCODEField;
            }
            set {
                this.wCODEField = value;
                this.RaisePropertyChanged("WCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string WDESC {
            get {
                return this.wDESCField;
            }
            set {
                this.wDESCField = value;
                this.RaisePropertyChanged("WDESC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public partial class ERRORDETAILSType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eCODEField;
        
        private string eDESCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ECODE {
            get {
                return this.eCODEField;
            }
            set {
                this.eCODEField = value;
                this.RaisePropertyChanged("ECODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EDESC {
            get {
                return this.eDESCField;
            }
            set {
                this.eDESCField = value;
                this.RaisePropertyChanged("EDESC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public partial class UDFDETAILSType2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fLDNAMField;
        
        private string fLDVALField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FLDNAM {
            get {
                return this.fLDNAMField;
            }
            set {
                this.fLDNAMField = value;
                this.RaisePropertyChanged("FLDNAM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FLDVAL {
            get {
                return this.fLDVALField;
            }
            set {
                this.fLDVALField = value;
                this.RaisePropertyChanged("FLDVAL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="FinancialCycle-Full-Type", Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public partial class FinancialCycleFullType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fINCLEField;
        
        private System.DateTime fCSTDTField;
        
        private string dESCRIPTIONField;
        
        private System.DateTime fC_END_DATEField;
        
        private string mAKERField;
        
        private string mAKERSTAMPField;
        
        private string cHECKERField;
        
        private string cHECKERSTAMPField;
        
        private decimal mODNOField;
        
        private bool mODNOFieldSpecified;
        
        private string tXNSTATField;
        
        private string aUTHSTATField;
        
        private FinancialCycleFullTypeStprdcds[] stprdcdsField;
        
        private UDFDETAILSType2[] uDFDETAILSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FINCLE {
            get {
                return this.fINCLEField;
            }
            set {
                this.fINCLEField = value;
                this.RaisePropertyChanged("FINCLE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime FCSTDT {
            get {
                return this.fCSTDTField;
            }
            set {
                this.fCSTDTField = value;
                this.RaisePropertyChanged("FCSTDT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
                this.RaisePropertyChanged("DESCRIPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime FC_END_DATE {
            get {
                return this.fC_END_DATEField;
            }
            set {
                this.fC_END_DATEField = value;
                this.RaisePropertyChanged("FC_END_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MAKER {
            get {
                return this.mAKERField;
            }
            set {
                this.mAKERField = value;
                this.RaisePropertyChanged("MAKER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MAKERSTAMP {
            get {
                return this.mAKERSTAMPField;
            }
            set {
                this.mAKERSTAMPField = value;
                this.RaisePropertyChanged("MAKERSTAMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CHECKER {
            get {
                return this.cHECKERField;
            }
            set {
                this.cHECKERField = value;
                this.RaisePropertyChanged("CHECKER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CHECKERSTAMP {
            get {
                return this.cHECKERSTAMPField;
            }
            set {
                this.cHECKERSTAMPField = value;
                this.RaisePropertyChanged("CHECKERSTAMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal MODNO {
            get {
                return this.mODNOField;
            }
            set {
                this.mODNOField = value;
                this.RaisePropertyChanged("MODNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MODNOSpecified {
            get {
                return this.mODNOFieldSpecified;
            }
            set {
                this.mODNOFieldSpecified = value;
                this.RaisePropertyChanged("MODNOSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string TXNSTAT {
            get {
                return this.tXNSTATField;
            }
            set {
                this.tXNSTATField = value;
                this.RaisePropertyChanged("TXNSTAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string AUTHSTAT {
            get {
                return this.aUTHSTATField;
            }
            set {
                this.aUTHSTATField = value;
                this.RaisePropertyChanged("AUTHSTAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stprdcds", Order=11)]
        public FinancialCycleFullTypeStprdcds[] Stprdcds {
            get {
                return this.stprdcdsField;
            }
            set {
                this.stprdcdsField = value;
                this.RaisePropertyChanged("Stprdcds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UDFDETAILS", Order=12)]
        public UDFDETAILSType2[] UDFDETAILS {
            get {
                return this.uDFDETAILSField;
            }
            set {
                this.uDFDETAILSField = value;
                this.RaisePropertyChanged("UDFDETAILS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public partial class FinancialCycleFullTypeStprdcds : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pERIOD_CODEField;
        
        private System.DateTime fC_START_DATEField;
        
        private bool fC_START_DATEFieldSpecified;
        
        private System.DateTime fC_END_DATEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PERIOD_CODE {
            get {
                return this.pERIOD_CODEField;
            }
            set {
                this.pERIOD_CODEField = value;
                this.RaisePropertyChanged("PERIOD_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime FC_START_DATE {
            get {
                return this.fC_START_DATEField;
            }
            set {
                this.fC_START_DATEField = value;
                this.RaisePropertyChanged("FC_START_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FC_START_DATESpecified {
            get {
                return this.fC_START_DATEFieldSpecified;
            }
            set {
                this.fC_START_DATEFieldSpecified = value;
                this.RaisePropertyChanged("FC_START_DATESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime FC_END_DATE {
            get {
                return this.fC_END_DATEField;
            }
            set {
                this.fC_END_DATEField = value;
                this.RaisePropertyChanged("FC_END_DATE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="FinancialCycle-PK-Type", Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public partial class FinancialCyclePKType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fINCLEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FINCLE {
            get {
                return this.fINCLEField;
            }
            set {
                this.fINCLEField = value;
                this.RaisePropertyChanged("FINCLE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public partial class FINANCIALCYCLEQUERY_IOFS_REQFCUBS_BODY : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FinancialCyclePKType financialCycleIOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Financial-Cycle-IO", Order=0)]
        public FinancialCyclePKType FinancialCycleIO {
            get {
                return this.financialCycleIOField;
            }
            set {
                this.financialCycleIOField = value;
                this.RaisePropertyChanged("FinancialCycleIO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public partial class FINANCIALCYCLEQUERY_IOFS_RES : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FCUBS_HEADERType fCUBS_HEADERField;
        
        private FINANCIALCYCLEQUERY_IOFS_RESFCUBS_BODY fCUBS_BODYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FCUBS_HEADERType FCUBS_HEADER {
            get {
                return this.fCUBS_HEADERField;
            }
            set {
                this.fCUBS_HEADERField = value;
                this.RaisePropertyChanged("FCUBS_HEADER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FINANCIALCYCLEQUERY_IOFS_RESFCUBS_BODY FCUBS_BODY {
            get {
                return this.fCUBS_BODYField;
            }
            set {
                this.fCUBS_BODYField = value;
                this.RaisePropertyChanged("FCUBS_BODY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public partial class FINANCIALCYCLEQUERY_IOFS_RESFCUBS_BODY : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FinancialCyclePKType financialCycleIOField;
        
        private FinancialCycleFullType financialCycleFullField;
        
        private ERRORDETAILSType[] fCUBS_ERROR_RESPField;
        
        private WARNINGDETAILSType[] fCUBS_WARNING_RESPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Financial-Cycle-IO", Order=0)]
        public FinancialCyclePKType FinancialCycleIO {
            get {
                return this.financialCycleIOField;
            }
            set {
                this.financialCycleIOField = value;
                this.RaisePropertyChanged("FinancialCycleIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Financial-Cycle-Full", Order=1)]
        public FinancialCycleFullType FinancialCycleFull {
            get {
                return this.financialCycleFullField;
            }
            set {
                this.financialCycleFullField = value;
                this.RaisePropertyChanged("FinancialCycleFull");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ERROR", typeof(ERRORDETAILSType), IsNullable=false)]
        public ERRORDETAILSType[] FCUBS_ERROR_RESP {
            get {
                return this.fCUBS_ERROR_RESPField;
            }
            set {
                this.fCUBS_ERROR_RESPField = value;
                this.RaisePropertyChanged("FCUBS_ERROR_RESP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("WARNING", typeof(WARNINGDETAILSType), IsNullable=false)]
        public WARNINGDETAILSType[] FCUBS_WARNING_RESP {
            get {
                return this.fCUBS_WARNING_RESPField;
            }
            set {
                this.fCUBS_WARNING_RESPField = value;
                this.RaisePropertyChanged("FCUBS_WARNING_RESP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FinancialCycleQueryIORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService", Order=0)]
        public IMPSTransactionRouter.FCUBSAccFinService.FINANCIALCYCLEQUERY_IOFS_REQ FINANCIALCYCLEQUERY_IOFS_REQ;
        
        public FinancialCycleQueryIORequest() {
        }
        
        public FinancialCycleQueryIORequest(IMPSTransactionRouter.FCUBSAccFinService.FINANCIALCYCLEQUERY_IOFS_REQ FINANCIALCYCLEQUERY_IOFS_REQ) {
            this.FINANCIALCYCLEQUERY_IOFS_REQ = FINANCIALCYCLEQUERY_IOFS_REQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FinancialCycleQueryIOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService", Order=0)]
        public IMPSTransactionRouter.FCUBSAccFinService.FINANCIALCYCLEQUERY_IOFS_RES FINANCIALCYCLEQUERY_IOFS_RES;
        
        public FinancialCycleQueryIOResponse() {
        }
        
        public FinancialCycleQueryIOResponse(IMPSTransactionRouter.FCUBSAccFinService.FINANCIALCYCLEQUERY_IOFS_RES FINANCIALCYCLEQUERY_IOFS_RES) {
            this.FINANCIALCYCLEQUERY_IOFS_RES = FINANCIALCYCLEQUERY_IOFS_RES;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public partial class QUERYFINANCIALCYCLE_IOFS_REQ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FCUBS_HEADERType fCUBS_HEADERField;
        
        private QUERYFINANCIALCYCLE_IOFS_REQFCUBS_BODY fCUBS_BODYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FCUBS_HEADERType FCUBS_HEADER {
            get {
                return this.fCUBS_HEADERField;
            }
            set {
                this.fCUBS_HEADERField = value;
                this.RaisePropertyChanged("FCUBS_HEADER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public QUERYFINANCIALCYCLE_IOFS_REQFCUBS_BODY FCUBS_BODY {
            get {
                return this.fCUBS_BODYField;
            }
            set {
                this.fCUBS_BODYField = value;
                this.RaisePropertyChanged("FCUBS_BODY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public partial class QUERYFINANCIALCYCLE_IOFS_REQFCUBS_BODY : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FinancialCycleQueryIOType stfincleIOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stfincle-IO", Order=0)]
        public FinancialCycleQueryIOType StfincleIO {
            get {
                return this.stfincleIOField;
            }
            set {
                this.stfincleIOField = value;
                this.RaisePropertyChanged("StfincleIO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public partial class QUERYFINANCIALCYCLE_IOFS_RES : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FCUBS_HEADERType fCUBS_HEADERField;
        
        private QUERYFINANCIALCYCLE_IOFS_RESFCUBS_BODY fCUBS_BODYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FCUBS_HEADERType FCUBS_HEADER {
            get {
                return this.fCUBS_HEADERField;
            }
            set {
                this.fCUBS_HEADERField = value;
                this.RaisePropertyChanged("FCUBS_HEADER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public QUERYFINANCIALCYCLE_IOFS_RESFCUBS_BODY FCUBS_BODY {
            get {
                return this.fCUBS_BODYField;
            }
            set {
                this.fCUBS_BODYField = value;
                this.RaisePropertyChanged("FCUBS_BODY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public partial class QUERYFINANCIALCYCLE_IOFS_RESFCUBS_BODY : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FinancialCycleQueryIOType stfincleIOField;
        
        private FinancialCycleFullType stfincleFullField;
        
        private ERRORDETAILSType[] fCUBS_ERROR_RESPField;
        
        private WARNINGDETAILSType[] fCUBS_WARNING_RESPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stfincle-IO", Order=0)]
        public FinancialCycleQueryIOType StfincleIO {
            get {
                return this.stfincleIOField;
            }
            set {
                this.stfincleIOField = value;
                this.RaisePropertyChanged("StfincleIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stfincle-Full", Order=1)]
        public FinancialCycleFullType StfincleFull {
            get {
                return this.stfincleFullField;
            }
            set {
                this.stfincleFullField = value;
                this.RaisePropertyChanged("StfincleFull");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ERROR", IsNullable=false)]
        public ERRORDETAILSType[] FCUBS_ERROR_RESP {
            get {
                return this.fCUBS_ERROR_RESPField;
            }
            set {
                this.fCUBS_ERROR_RESPField = value;
                this.RaisePropertyChanged("FCUBS_ERROR_RESP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("WARNING", IsNullable=false)]
        public WARNINGDETAILSType[] FCUBS_WARNING_RESP {
            get {
                return this.fCUBS_WARNING_RESPField;
            }
            set {
                this.fCUBS_WARNING_RESPField = value;
                this.RaisePropertyChanged("FCUBS_WARNING_RESP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryFinancialCycleIORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService", Order=0)]
        public IMPSTransactionRouter.FCUBSAccFinService.QUERYFINANCIALCYCLE_IOFS_REQ QUERYFINANCIALCYCLE_IOFS_REQ;
        
        public QueryFinancialCycleIORequest() {
        }
        
        public QueryFinancialCycleIORequest(IMPSTransactionRouter.FCUBSAccFinService.QUERYFINANCIALCYCLE_IOFS_REQ QUERYFINANCIALCYCLE_IOFS_REQ) {
            this.QUERYFINANCIALCYCLE_IOFS_REQ = QUERYFINANCIALCYCLE_IOFS_REQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryFinancialCycleIOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService", Order=0)]
        public IMPSTransactionRouter.FCUBSAccFinService.QUERYFINANCIALCYCLE_IOFS_RES QUERYFINANCIALCYCLE_IOFS_RES;
        
        public QueryFinancialCycleIOResponse() {
        }
        
        public QueryFinancialCycleIOResponse(IMPSTransactionRouter.FCUBSAccFinService.QUERYFINANCIALCYCLE_IOFS_RES QUERYFINANCIALCYCLE_IOFS_RES) {
            this.QUERYFINANCIALCYCLE_IOFS_RES = QUERYFINANCIALCYCLE_IOFS_RES;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public partial class REQUESTACCSTMT_IOFS_REQ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FCUBS_HEADERType fCUBS_HEADERField;
        
        private REQUESTACCSTMT_IOFS_REQFCUBS_BODY fCUBS_BODYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FCUBS_HEADERType FCUBS_HEADER {
            get {
                return this.fCUBS_HEADERField;
            }
            set {
                this.fCUBS_HEADERField = value;
                this.RaisePropertyChanged("FCUBS_HEADER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public REQUESTACCSTMT_IOFS_REQFCUBS_BODY FCUBS_BODY {
            get {
                return this.fCUBS_BODYField;
            }
            set {
                this.fCUBS_BODYField = value;
                this.RaisePropertyChanged("FCUBS_BODY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public partial class REQUESTACCSTMT_IOFS_REQFCUBS_BODY : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AdhocStmtReqType custAccStmtAdhocRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AdhocStmtReqType CustAccStmtAdhocRequest {
            get {
                return this.custAccStmtAdhocRequestField;
            }
            set {
                this.custAccStmtAdhocRequestField = value;
                this.RaisePropertyChanged("CustAccStmtAdhocRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public partial class REQUESTACCSTMT_IOFS_RES : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FCUBS_HEADERType fCUBS_HEADERField;
        
        private REQUESTACCSTMT_IOFS_RESFCUBS_BODY fCUBS_BODYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FCUBS_HEADERType FCUBS_HEADER {
            get {
                return this.fCUBS_HEADERField;
            }
            set {
                this.fCUBS_HEADERField = value;
                this.RaisePropertyChanged("FCUBS_HEADER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public REQUESTACCSTMT_IOFS_RESFCUBS_BODY FCUBS_BODY {
            get {
                return this.fCUBS_BODYField;
            }
            set {
                this.fCUBS_BODYField = value;
                this.RaisePropertyChanged("FCUBS_BODY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService")]
    public partial class REQUESTACCSTMT_IOFS_RESFCUBS_BODY : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AdhocStmtResType custAccStmtAdhocRequestField;
        
        private ERRORDETAILSType[] fCUBS_ERROR_RESPField;
        
        private WARNINGDETAILSType[] fCUBS_WARNING_RESPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AdhocStmtResType CustAccStmtAdhocRequest {
            get {
                return this.custAccStmtAdhocRequestField;
            }
            set {
                this.custAccStmtAdhocRequestField = value;
                this.RaisePropertyChanged("CustAccStmtAdhocRequest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ERROR", IsNullable=false)]
        public ERRORDETAILSType[] FCUBS_ERROR_RESP {
            get {
                return this.fCUBS_ERROR_RESPField;
            }
            set {
                this.fCUBS_ERROR_RESPField = value;
                this.RaisePropertyChanged("FCUBS_ERROR_RESP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("WARNING", IsNullable=false)]
        public WARNINGDETAILSType[] FCUBS_WARNING_RESP {
            get {
                return this.fCUBS_WARNING_RESPField;
            }
            set {
                this.fCUBS_WARNING_RESPField = value;
                this.RaisePropertyChanged("FCUBS_WARNING_RESP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestAccStmtIORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService", Order=0)]
        public IMPSTransactionRouter.FCUBSAccFinService.REQUESTACCSTMT_IOFS_REQ REQUESTACCSTMT_IOFS_REQ;
        
        public RequestAccStmtIORequest() {
        }
        
        public RequestAccStmtIORequest(IMPSTransactionRouter.FCUBSAccFinService.REQUESTACCSTMT_IOFS_REQ REQUESTACCSTMT_IOFS_REQ) {
            this.REQUESTACCSTMT_IOFS_REQ = REQUESTACCSTMT_IOFS_REQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestAccStmtIOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fcubs.ofss.com/service/FCUBSAccFinService", Order=0)]
        public IMPSTransactionRouter.FCUBSAccFinService.REQUESTACCSTMT_IOFS_RES REQUESTACCSTMT_IOFS_RES;
        
        public RequestAccStmtIOResponse() {
        }
        
        public RequestAccStmtIOResponse(IMPSTransactionRouter.FCUBSAccFinService.REQUESTACCSTMT_IOFS_RES REQUESTACCSTMT_IOFS_RES) {
            this.REQUESTACCSTMT_IOFS_RES = REQUESTACCSTMT_IOFS_RES;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FCUBSAccFinServiceSEIChannel : IMPSTransactionRouter.FCUBSAccFinService.FCUBSAccFinServiceSEI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FCUBSAccFinServiceSEIClient : System.ServiceModel.ClientBase<IMPSTransactionRouter.FCUBSAccFinService.FCUBSAccFinServiceSEI>, IMPSTransactionRouter.FCUBSAccFinService.FCUBSAccFinServiceSEI {
        
        public FCUBSAccFinServiceSEIClient() {
        }
        
        public FCUBSAccFinServiceSEIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FCUBSAccFinServiceSEIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FCUBSAccFinServiceSEIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FCUBSAccFinServiceSEIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IMPSTransactionRouter.FCUBSAccFinService.FinancialCycleQueryIOResponse IMPSTransactionRouter.FCUBSAccFinService.FCUBSAccFinServiceSEI.FinancialCycleQueryIO(IMPSTransactionRouter.FCUBSAccFinService.FinancialCycleQueryIORequest request) {
            return base.Channel.FinancialCycleQueryIO(request);
        }
        
        public IMPSTransactionRouter.FCUBSAccFinService.FINANCIALCYCLEQUERY_IOFS_RES FinancialCycleQueryIO(IMPSTransactionRouter.FCUBSAccFinService.FINANCIALCYCLEQUERY_IOFS_REQ FINANCIALCYCLEQUERY_IOFS_REQ) {
            IMPSTransactionRouter.FCUBSAccFinService.FinancialCycleQueryIORequest inValue = new IMPSTransactionRouter.FCUBSAccFinService.FinancialCycleQueryIORequest();
            inValue.FINANCIALCYCLEQUERY_IOFS_REQ = FINANCIALCYCLEQUERY_IOFS_REQ;
            IMPSTransactionRouter.FCUBSAccFinService.FinancialCycleQueryIOResponse retVal = ((IMPSTransactionRouter.FCUBSAccFinService.FCUBSAccFinServiceSEI)(this)).FinancialCycleQueryIO(inValue);
            return retVal.FINANCIALCYCLEQUERY_IOFS_RES;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IMPSTransactionRouter.FCUBSAccFinService.FinancialCycleQueryIOResponse> IMPSTransactionRouter.FCUBSAccFinService.FCUBSAccFinServiceSEI.FinancialCycleQueryIOAsync(IMPSTransactionRouter.FCUBSAccFinService.FinancialCycleQueryIORequest request) {
            return base.Channel.FinancialCycleQueryIOAsync(request);
        }
        
        public System.Threading.Tasks.Task<IMPSTransactionRouter.FCUBSAccFinService.FinancialCycleQueryIOResponse> FinancialCycleQueryIOAsync(IMPSTransactionRouter.FCUBSAccFinService.FINANCIALCYCLEQUERY_IOFS_REQ FINANCIALCYCLEQUERY_IOFS_REQ) {
            IMPSTransactionRouter.FCUBSAccFinService.FinancialCycleQueryIORequest inValue = new IMPSTransactionRouter.FCUBSAccFinService.FinancialCycleQueryIORequest();
            inValue.FINANCIALCYCLEQUERY_IOFS_REQ = FINANCIALCYCLEQUERY_IOFS_REQ;
            return ((IMPSTransactionRouter.FCUBSAccFinService.FCUBSAccFinServiceSEI)(this)).FinancialCycleQueryIOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IMPSTransactionRouter.FCUBSAccFinService.QueryFinancialCycleIOResponse IMPSTransactionRouter.FCUBSAccFinService.FCUBSAccFinServiceSEI.QueryFinancialCycleIO(IMPSTransactionRouter.FCUBSAccFinService.QueryFinancialCycleIORequest request) {
            return base.Channel.QueryFinancialCycleIO(request);
        }
        
        public IMPSTransactionRouter.FCUBSAccFinService.QUERYFINANCIALCYCLE_IOFS_RES QueryFinancialCycleIO(IMPSTransactionRouter.FCUBSAccFinService.QUERYFINANCIALCYCLE_IOFS_REQ QUERYFINANCIALCYCLE_IOFS_REQ) {
            IMPSTransactionRouter.FCUBSAccFinService.QueryFinancialCycleIORequest inValue = new IMPSTransactionRouter.FCUBSAccFinService.QueryFinancialCycleIORequest();
            inValue.QUERYFINANCIALCYCLE_IOFS_REQ = QUERYFINANCIALCYCLE_IOFS_REQ;
            IMPSTransactionRouter.FCUBSAccFinService.QueryFinancialCycleIOResponse retVal = ((IMPSTransactionRouter.FCUBSAccFinService.FCUBSAccFinServiceSEI)(this)).QueryFinancialCycleIO(inValue);
            return retVal.QUERYFINANCIALCYCLE_IOFS_RES;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IMPSTransactionRouter.FCUBSAccFinService.QueryFinancialCycleIOResponse> IMPSTransactionRouter.FCUBSAccFinService.FCUBSAccFinServiceSEI.QueryFinancialCycleIOAsync(IMPSTransactionRouter.FCUBSAccFinService.QueryFinancialCycleIORequest request) {
            return base.Channel.QueryFinancialCycleIOAsync(request);
        }
        
        public System.Threading.Tasks.Task<IMPSTransactionRouter.FCUBSAccFinService.QueryFinancialCycleIOResponse> QueryFinancialCycleIOAsync(IMPSTransactionRouter.FCUBSAccFinService.QUERYFINANCIALCYCLE_IOFS_REQ QUERYFINANCIALCYCLE_IOFS_REQ) {
            IMPSTransactionRouter.FCUBSAccFinService.QueryFinancialCycleIORequest inValue = new IMPSTransactionRouter.FCUBSAccFinService.QueryFinancialCycleIORequest();
            inValue.QUERYFINANCIALCYCLE_IOFS_REQ = QUERYFINANCIALCYCLE_IOFS_REQ;
            return ((IMPSTransactionRouter.FCUBSAccFinService.FCUBSAccFinServiceSEI)(this)).QueryFinancialCycleIOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IMPSTransactionRouter.FCUBSAccFinService.RequestAccStmtIOResponse IMPSTransactionRouter.FCUBSAccFinService.FCUBSAccFinServiceSEI.RequestAccStmtIO(IMPSTransactionRouter.FCUBSAccFinService.RequestAccStmtIORequest request) {
            return base.Channel.RequestAccStmtIO(request);
        }
        
        public IMPSTransactionRouter.FCUBSAccFinService.REQUESTACCSTMT_IOFS_RES RequestAccStmtIO(IMPSTransactionRouter.FCUBSAccFinService.REQUESTACCSTMT_IOFS_REQ REQUESTACCSTMT_IOFS_REQ) {
            IMPSTransactionRouter.FCUBSAccFinService.RequestAccStmtIORequest inValue = new IMPSTransactionRouter.FCUBSAccFinService.RequestAccStmtIORequest();
            inValue.REQUESTACCSTMT_IOFS_REQ = REQUESTACCSTMT_IOFS_REQ;
            IMPSTransactionRouter.FCUBSAccFinService.RequestAccStmtIOResponse retVal = ((IMPSTransactionRouter.FCUBSAccFinService.FCUBSAccFinServiceSEI)(this)).RequestAccStmtIO(inValue);
            return retVal.REQUESTACCSTMT_IOFS_RES;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IMPSTransactionRouter.FCUBSAccFinService.RequestAccStmtIOResponse> IMPSTransactionRouter.FCUBSAccFinService.FCUBSAccFinServiceSEI.RequestAccStmtIOAsync(IMPSTransactionRouter.FCUBSAccFinService.RequestAccStmtIORequest request) {
            return base.Channel.RequestAccStmtIOAsync(request);
        }
        
        public System.Threading.Tasks.Task<IMPSTransactionRouter.FCUBSAccFinService.RequestAccStmtIOResponse> RequestAccStmtIOAsync(IMPSTransactionRouter.FCUBSAccFinService.REQUESTACCSTMT_IOFS_REQ REQUESTACCSTMT_IOFS_REQ) {
            IMPSTransactionRouter.FCUBSAccFinService.RequestAccStmtIORequest inValue = new IMPSTransactionRouter.FCUBSAccFinService.RequestAccStmtIORequest();
            inValue.REQUESTACCSTMT_IOFS_REQ = REQUESTACCSTMT_IOFS_REQ;
            return ((IMPSTransactionRouter.FCUBSAccFinService.FCUBSAccFinServiceSEI)(this)).RequestAccStmtIOAsync(inValue);
        }
    }
}
