//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMPSTransactionRouter.RRCO {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.bob.ramis.cmcltd.com/")]
    public partial class BobFaultBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultCodeField;
        
        private string faultStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("faultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultString {
            get {
                return this.faultStringField;
            }
            set {
                this.faultStringField = value;
                this.RaisePropertyChanged("faultString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.bob.ramis.cmcltd.com/")]
    public partial class DepositVoucherMaster : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string depositVoucherNoField;
        
        private string tpnField;
        
        private string nameField;
        
        private System.DateTime depVouDueDateField;
        
        private decimal depVouDueAmountField;
        
        private string responseTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string depositVoucherNo {
            get {
                return this.depositVoucherNoField;
            }
            set {
                this.depositVoucherNoField = value;
                this.RaisePropertyChanged("depositVoucherNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tpn {
            get {
                return this.tpnField;
            }
            set {
                this.tpnField = value;
                this.RaisePropertyChanged("tpn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime depVouDueDate {
            get {
                return this.depVouDueDateField;
            }
            set {
                this.depVouDueDateField = value;
                this.RaisePropertyChanged("depVouDueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal depVouDueAmount {
            get {
                return this.depVouDueAmountField;
            }
            set {
                this.depVouDueAmountField = value;
                this.RaisePropertyChanged("depVouDueAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string responseToken {
            get {
                return this.responseTokenField;
            }
            set {
                this.responseTokenField = value;
                this.RaisePropertyChanged("responseToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.bob.ramis.cmcltd.com/", ConfigurationName="RRCO.BobIntegrationService")]
    public interface BobIntegrationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bob.ramis.cmcltd.com/BobIntegrationService/initRequest", ReplyAction="http://service.bob.ramis.cmcltd.com/BobIntegrationService/initResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void init();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bob.ramis.cmcltd.com/BobIntegrationService/initRequest", ReplyAction="http://service.bob.ramis.cmcltd.com/BobIntegrationService/initResponse")]
        System.Threading.Tasks.Task initAsync();
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bob.ramis.cmcltd.com/BobIntegrationService/getDepositVoucherDetail" +
            "sRequest", ReplyAction="http://service.bob.ramis.cmcltd.com/BobIntegrationService/getDepositVoucherDetail" +
            "sResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMPSTransactionRouter.RRCO.BobFaultBean), Action="http://service.bob.ramis.cmcltd.com/BobIntegrationService/getDepositVoucherDetail" +
            "s/Fault/BobException", Name="BobFaultBean", Namespace="http://service.bob.ramis.cmcltd.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        IMPSTransactionRouter.RRCO.getDepositVoucherDetailsResponse getDepositVoucherDetails(IMPSTransactionRouter.RRCO.getDepositVoucherDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bob.ramis.cmcltd.com/BobIntegrationService/getDepositVoucherDetail" +
            "sRequest", ReplyAction="http://service.bob.ramis.cmcltd.com/BobIntegrationService/getDepositVoucherDetail" +
            "sResponse")]
        System.Threading.Tasks.Task<IMPSTransactionRouter.RRCO.getDepositVoucherDetailsResponse> getDepositVoucherDetailsAsync(IMPSTransactionRouter.RRCO.getDepositVoucherDetailsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bob.ramis.cmcltd.com/BobIntegrationService/getChallanDetailsReques" +
            "t", ReplyAction="http://service.bob.ramis.cmcltd.com/BobIntegrationService/getChallanDetailsRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMPSTransactionRouter.RRCO.BobFaultBean), Action="http://service.bob.ramis.cmcltd.com/BobIntegrationService/getChallanDetails/Fault" +
            "/BobException", Name="BobFaultBean", Namespace="http://service.bob.ramis.cmcltd.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        IMPSTransactionRouter.RRCO.getChallanDetailsResponse getChallanDetails(IMPSTransactionRouter.RRCO.getChallanDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bob.ramis.cmcltd.com/BobIntegrationService/getChallanDetailsReques" +
            "t", ReplyAction="http://service.bob.ramis.cmcltd.com/BobIntegrationService/getChallanDetailsRespon" +
            "se")]
        System.Threading.Tasks.Task<IMPSTransactionRouter.RRCO.getChallanDetailsResponse> getChallanDetailsAsync(IMPSTransactionRouter.RRCO.getChallanDetailsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bob.ramis.cmcltd.com/BobIntegrationService/sendPaymentStatusReques" +
            "t", ReplyAction="http://service.bob.ramis.cmcltd.com/BobIntegrationService/sendPaymentStatusRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMPSTransactionRouter.RRCO.BobFaultBean), Action="http://service.bob.ramis.cmcltd.com/BobIntegrationService/sendPaymentStatus/Fault" +
            "/BobException", Name="BobFaultBean", Namespace="http://service.bob.ramis.cmcltd.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        IMPSTransactionRouter.RRCO.sendPaymentStatusResponse sendPaymentStatus(IMPSTransactionRouter.RRCO.sendPaymentStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bob.ramis.cmcltd.com/BobIntegrationService/sendPaymentStatusReques" +
            "t", ReplyAction="http://service.bob.ramis.cmcltd.com/BobIntegrationService/sendPaymentStatusRespon" +
            "se")]
        System.Threading.Tasks.Task<IMPSTransactionRouter.RRCO.sendPaymentStatusResponse> sendPaymentStatusAsync(IMPSTransactionRouter.RRCO.sendPaymentStatusRequest request);
        
        // CODEGEN: Parameter 'responseToken' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://service.bob.ramis.cmcltd.com/BobIntegrationService/sendAcknowledgement")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void sendAcknowledgement(IMPSTransactionRouter.RRCO.sendAcknowledgement request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://service.bob.ramis.cmcltd.com/BobIntegrationService/sendAcknowledgement")]
        System.Threading.Tasks.Task sendAcknowledgementAsync(IMPSTransactionRouter.RRCO.sendAcknowledgement request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDepositVoucherDetails", WrapperNamespace="http://service.bob.ramis.cmcltd.com/", IsWrapped=true)]
    public partial class getDepositVoucherDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bob.ramis.cmcltd.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string depVouNo;
        
        public getDepositVoucherDetailsRequest() {
        }
        
        public getDepositVoucherDetailsRequest(string depVouNo) {
            this.depVouNo = depVouNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDepositVoucherDetailsResponse", WrapperNamespace="http://service.bob.ramis.cmcltd.com/", IsWrapped=true)]
    public partial class getDepositVoucherDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bob.ramis.cmcltd.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IMPSTransactionRouter.RRCO.DepositVoucherMaster @return;
        
        public getDepositVoucherDetailsResponse() {
        }
        
        public getDepositVoucherDetailsResponse(IMPSTransactionRouter.RRCO.DepositVoucherMaster @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.bob.ramis.cmcltd.com/")]
    public partial class DepositChallanMaster : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string depositChallanNumberField;
        
        private string agencyCodeField;
        
        private System.DateTime depositDateField;
        
        private decimal depositChallanAmountField;
        
        private string paymentModeField;
        
        private string responseTokenField;
        
        private InstrumentDetail[] instrumentDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string depositChallanNumber {
            get {
                return this.depositChallanNumberField;
            }
            set {
                this.depositChallanNumberField = value;
                this.RaisePropertyChanged("depositChallanNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string agencyCode {
            get {
                return this.agencyCodeField;
            }
            set {
                this.agencyCodeField = value;
                this.RaisePropertyChanged("agencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime depositDate {
            get {
                return this.depositDateField;
            }
            set {
                this.depositDateField = value;
                this.RaisePropertyChanged("depositDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal depositChallanAmount {
            get {
                return this.depositChallanAmountField;
            }
            set {
                this.depositChallanAmountField = value;
                this.RaisePropertyChanged("depositChallanAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string paymentMode {
            get {
                return this.paymentModeField;
            }
            set {
                this.paymentModeField = value;
                this.RaisePropertyChanged("paymentMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string responseToken {
            get {
                return this.responseTokenField;
            }
            set {
                this.responseTokenField = value;
                this.RaisePropertyChanged("responseToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("instrumentDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public InstrumentDetail[] instrumentDetails {
            get {
                return this.instrumentDetailsField;
            }
            set {
                this.instrumentDetailsField = value;
                this.RaisePropertyChanged("instrumentDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.bob.ramis.cmcltd.com/")]
    public partial class InstrumentDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string instrumentNumberField;
        
        private System.DateTime instrumentDateField;
        
        private decimal instrumentAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string instrumentNumber {
            get {
                return this.instrumentNumberField;
            }
            set {
                this.instrumentNumberField = value;
                this.RaisePropertyChanged("instrumentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime instrumentDate {
            get {
                return this.instrumentDateField;
            }
            set {
                this.instrumentDateField = value;
                this.RaisePropertyChanged("instrumentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal instrumentAmount {
            get {
                return this.instrumentAmountField;
            }
            set {
                this.instrumentAmountField = value;
                this.RaisePropertyChanged("instrumentAmount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getChallanDetails", WrapperNamespace="http://service.bob.ramis.cmcltd.com/", IsWrapped=true)]
    public partial class getChallanDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bob.ramis.cmcltd.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string depChlnNo;
        
        public getChallanDetailsRequest() {
        }
        
        public getChallanDetailsRequest(string depChlnNo) {
            this.depChlnNo = depChlnNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getChallanDetailsResponse", WrapperNamespace="http://service.bob.ramis.cmcltd.com/", IsWrapped=true)]
    public partial class getChallanDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bob.ramis.cmcltd.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IMPSTransactionRouter.RRCO.DepositChallanMaster @return;
        
        public getChallanDetailsResponse() {
        }
        
        public getChallanDetailsResponse(IMPSTransactionRouter.RRCO.DepositChallanMaster @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendPaymentStatus", WrapperNamespace="http://service.bob.ramis.cmcltd.com/", IsWrapped=true)]
    public partial class sendPaymentStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bob.ramis.cmcltd.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string depVouNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bob.ramis.cmcltd.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int status;
        
        public sendPaymentStatusRequest() {
        }
        
        public sendPaymentStatusRequest(string depVouNo, int status) {
            this.depVouNo = depVouNo;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendPaymentStatusResponse", WrapperNamespace="http://service.bob.ramis.cmcltd.com/", IsWrapped=true)]
    public partial class sendPaymentStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bob.ramis.cmcltd.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public sendPaymentStatusResponse() {
        }
        
        public sendPaymentStatusResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendAcknowledgement", WrapperNamespace="http://service.bob.ramis.cmcltd.com/", IsWrapped=true)]
    public partial class sendAcknowledgement {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bob.ramis.cmcltd.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string responseToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bob.ramis.cmcltd.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int status;
        
        public sendAcknowledgement() {
        }
        
        public sendAcknowledgement(string responseToken, int status) {
            this.responseToken = responseToken;
            this.status = status;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BobIntegrationServiceChannel : IMPSTransactionRouter.RRCO.BobIntegrationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BobIntegrationServiceClient : System.ServiceModel.ClientBase<IMPSTransactionRouter.RRCO.BobIntegrationService>, IMPSTransactionRouter.RRCO.BobIntegrationService {
        
        public BobIntegrationServiceClient() {
        }
        
        public BobIntegrationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BobIntegrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BobIntegrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BobIntegrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void init() {
            base.Channel.init();
        }
        
        public System.Threading.Tasks.Task initAsync() {
            return base.Channel.initAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IMPSTransactionRouter.RRCO.getDepositVoucherDetailsResponse IMPSTransactionRouter.RRCO.BobIntegrationService.getDepositVoucherDetails(IMPSTransactionRouter.RRCO.getDepositVoucherDetailsRequest request) {
            return base.Channel.getDepositVoucherDetails(request);
        }
        
        public IMPSTransactionRouter.RRCO.DepositVoucherMaster getDepositVoucherDetails(string depVouNo) {
            IMPSTransactionRouter.RRCO.getDepositVoucherDetailsRequest inValue = new IMPSTransactionRouter.RRCO.getDepositVoucherDetailsRequest();
            inValue.depVouNo = depVouNo;
            IMPSTransactionRouter.RRCO.getDepositVoucherDetailsResponse retVal = ((IMPSTransactionRouter.RRCO.BobIntegrationService)(this)).getDepositVoucherDetails(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IMPSTransactionRouter.RRCO.getDepositVoucherDetailsResponse> IMPSTransactionRouter.RRCO.BobIntegrationService.getDepositVoucherDetailsAsync(IMPSTransactionRouter.RRCO.getDepositVoucherDetailsRequest request) {
            return base.Channel.getDepositVoucherDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<IMPSTransactionRouter.RRCO.getDepositVoucherDetailsResponse> getDepositVoucherDetailsAsync(string depVouNo) {
            IMPSTransactionRouter.RRCO.getDepositVoucherDetailsRequest inValue = new IMPSTransactionRouter.RRCO.getDepositVoucherDetailsRequest();
            inValue.depVouNo = depVouNo;
            return ((IMPSTransactionRouter.RRCO.BobIntegrationService)(this)).getDepositVoucherDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IMPSTransactionRouter.RRCO.getChallanDetailsResponse IMPSTransactionRouter.RRCO.BobIntegrationService.getChallanDetails(IMPSTransactionRouter.RRCO.getChallanDetailsRequest request) {
            return base.Channel.getChallanDetails(request);
        }
        
        public IMPSTransactionRouter.RRCO.DepositChallanMaster getChallanDetails(string depChlnNo) {
            IMPSTransactionRouter.RRCO.getChallanDetailsRequest inValue = new IMPSTransactionRouter.RRCO.getChallanDetailsRequest();
            inValue.depChlnNo = depChlnNo;
            IMPSTransactionRouter.RRCO.getChallanDetailsResponse retVal = ((IMPSTransactionRouter.RRCO.BobIntegrationService)(this)).getChallanDetails(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IMPSTransactionRouter.RRCO.getChallanDetailsResponse> IMPSTransactionRouter.RRCO.BobIntegrationService.getChallanDetailsAsync(IMPSTransactionRouter.RRCO.getChallanDetailsRequest request) {
            return base.Channel.getChallanDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<IMPSTransactionRouter.RRCO.getChallanDetailsResponse> getChallanDetailsAsync(string depChlnNo) {
            IMPSTransactionRouter.RRCO.getChallanDetailsRequest inValue = new IMPSTransactionRouter.RRCO.getChallanDetailsRequest();
            inValue.depChlnNo = depChlnNo;
            return ((IMPSTransactionRouter.RRCO.BobIntegrationService)(this)).getChallanDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IMPSTransactionRouter.RRCO.sendPaymentStatusResponse IMPSTransactionRouter.RRCO.BobIntegrationService.sendPaymentStatus(IMPSTransactionRouter.RRCO.sendPaymentStatusRequest request) {
            return base.Channel.sendPaymentStatus(request);
        }
        
        public int sendPaymentStatus(string depVouNo, int status) {
            IMPSTransactionRouter.RRCO.sendPaymentStatusRequest inValue = new IMPSTransactionRouter.RRCO.sendPaymentStatusRequest();
            inValue.depVouNo = depVouNo;
            inValue.status = status;
            IMPSTransactionRouter.RRCO.sendPaymentStatusResponse retVal = ((IMPSTransactionRouter.RRCO.BobIntegrationService)(this)).sendPaymentStatus(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IMPSTransactionRouter.RRCO.sendPaymentStatusResponse> IMPSTransactionRouter.RRCO.BobIntegrationService.sendPaymentStatusAsync(IMPSTransactionRouter.RRCO.sendPaymentStatusRequest request) {
            return base.Channel.sendPaymentStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<IMPSTransactionRouter.RRCO.sendPaymentStatusResponse> sendPaymentStatusAsync(string depVouNo, int status) {
            IMPSTransactionRouter.RRCO.sendPaymentStatusRequest inValue = new IMPSTransactionRouter.RRCO.sendPaymentStatusRequest();
            inValue.depVouNo = depVouNo;
            inValue.status = status;
            return ((IMPSTransactionRouter.RRCO.BobIntegrationService)(this)).sendPaymentStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void IMPSTransactionRouter.RRCO.BobIntegrationService.sendAcknowledgement(IMPSTransactionRouter.RRCO.sendAcknowledgement request) {
            base.Channel.sendAcknowledgement(request);
        }
        
        public void sendAcknowledgement(string responseToken, int status) {
            IMPSTransactionRouter.RRCO.sendAcknowledgement inValue = new IMPSTransactionRouter.RRCO.sendAcknowledgement();
            inValue.responseToken = responseToken;
            inValue.status = status;
            ((IMPSTransactionRouter.RRCO.BobIntegrationService)(this)).sendAcknowledgement(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task IMPSTransactionRouter.RRCO.BobIntegrationService.sendAcknowledgementAsync(IMPSTransactionRouter.RRCO.sendAcknowledgement request) {
            return base.Channel.sendAcknowledgementAsync(request);
        }
        
        public System.Threading.Tasks.Task sendAcknowledgementAsync(string responseToken, int status) {
            IMPSTransactionRouter.RRCO.sendAcknowledgement inValue = new IMPSTransactionRouter.RRCO.sendAcknowledgement();
            inValue.responseToken = responseToken;
            inValue.status = status;
            return ((IMPSTransactionRouter.RRCO.BobIntegrationService)(this)).sendAcknowledgementAsync(inValue);
        }
    }
}
